### ISSUE TITLE
Typo "streams may be either pull or pull" or am I misunderstanding?

### ISSUE THREAD

**Issue by beckyconning** [natefaubion/purescript-run-streaming#2]
https://github.com/natefaubion/purescript-run-streaming/blob/343d20b7d37c580bfa19486da5d08079b3ee38b6/src/Run/Streaming.purs#L2

**Comment by natefaubion** [comment]
Closed https://github.com/natefaubion/purescript-run-streaming/commit/1eb765d05bd4955e4b57f6d637a47998a95e58f1
